name = "smol-fe"
compatibility_date = "2024-04-03"
pages_build_output_dir = "dist"

[vars]
PUBLIC_API_URL = "https://api.smol.xyz"
PUBLIC_AUDIO_PROXY_URL = "/api"
PUBLIC_RPC_URL = "https://rpc.ankr.com/stellar_soroban"
PUBLIC_NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
PUBLIC_WALLET_WASM_HASH = "ecd990f0b45ca6817149b6175f79b32efb442f35731985a084131e8265c4cd90"
PUBLIC_KALE_SAC_ID = "CB23WRDQWGSP6YPMY4UV5C4OW5CBTXKYN3XEATG7KJEZCXMJBYEHOUOV"
PUBLIC_XLM_SAC_ID = "CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA"
PUBLIC_AGGREGATOR_CONTRACT_ID = "CAG5LRYQ5JVEUI5TEID72EYOVX44TTUJT5BQR2J6J77FH65PCCFAJDDH"
PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAABBPiK_8QHc6n8E4"
PUBLIC_SOROSWAP_API_KEY = "sk_4841707489b6c8a0ec4614bfa917be0b6518b0fd8b1f0cb08c0abe84de095b8f"
PUBLIC_RELAYER_URL = "https://api.kalefarm.xyz"
PUBLIC_RELAYER_API_KEY = "453552cd-3dd9-44a1-b344-066906059363" # Set this for Dev/Preview (Bypasses Turnstile)
# NOTE: Logic in client enforces this is ONLY used on pages.dev or localhost
# If set, defaults to OZ Channels URL: https://channels.openzeppelin.com
# Note: OpenZeppelin Channels integration is enabled when PUBLIC_RELAYER_API_KEY is present
# Otherwise defaults to KaleFarm API (https://api.kalefarm.xyz) with Turnstile verification
# PUBLIC_CHANNELS_API_KEY set in CF Dashboard (unused)
PUBLIC_SMOL_CONTRACT_ID = "CBRNUVLGFM5OYWAGZVGU7CTMP2UJLKZCLFY2ANUCK5UGKND6BBAA5PLA"


[[kv_namespaces]]
binding = "SESSION"
id = "preview-session-kv"
preview_id = "preview-session-kv"
